movie/app1/urls.py
from django.contrib import admin
from django.urls import path
from app1 import views
app_name='app1'
urlpatterns = [
    path('',views.home,name='home'),
    path('add',views.addmovie,name='add'),
    path('detail/<int:i>',views.detail,name='detail'),
    path('delete/<int:i>',views.delete,name="delete"),
    path('edit/<int:i>',views.edit,name="edit"),
]

movie/movie/urls.py
from django.contrib import admin
from django.urls import path
from  django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app1.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

movie/app1/models.py
from django.db import models

# Create your models here.
from django.db import models

class Movie(models.Model):   #table definition
    title=models.CharField(max_length=20)
    description=models.TextField()
    year=models.IntegerField()
    language=models.CharField(max_length=20)
    image=models.ImageField(upload_to='img',blank=True,null=True)

    def _str_(self):
        return self.title

movie/app1/views.py
from django.shortcuts import render

from app1.models import Movie


def home(request):
    k=Movie.objects.all()
    return render(request,'home.html',{'movie':k})
def addmovie(request):
   if(request.method=='POST'):
       t=request.POST['t']
       d = request.POST['d']
       y = request.POST['y']
       l = request.POST['l']
       i=request.FILES['i']

       m=Movie.objects.create(title=t,description=d,year=y,language=l,image=i)
       m.save()
       return home(request)

   return render(request,'add.html')


def detail(request,i):
    k=Movie.objects.get(id=i)

    return render(request,'detail.html',{'movie':k})


def delete(request,i):
    k=Movie.objects.get(id=i)
    k.delete()
    return home(request)



def edit(request,i):
    k=Movie.objects.get(id=i)
    if(request.method=="POST"):
        k.title=request.POST['t']
        k.description=request.POST['d']
        k.year=request.POST['y']

        k.languages=request.POST['l']

        if(request.FILES.get('i')==None):
            k.save()
        else:
            k.image=request.FILES.get('i')
        k.save()
        return home(request)


    return render(request,'edit.html',{'movie':k})

movie/templates/add.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<H2>MOVIES</H2>
<h2 class="text-center">Add Movies</h2>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-3">
  <label class="form-label">Title</label>
  <input type="text" class="form-control" name="t" >
</div>
<div class="mb-3">
  <label class="form-label">Description</label>
  <input type="text" class="form-control"  name='d' >
</div>
<div class="mb-3">
  <label class="form-label">year</label>
  <input type="number" class="form-control" name="y" >
</div>

<div class="mb-3">
  <label class="form-label">language</label>
  <input type="text" class="form-control" name="l" placeholder="enter the language">
</div>



    <div class="mb-3">
  <label class="form-label">image</label>
  <input type="file" class="form-control" name="i" >
</div>
<div class="mb-3">
    <input type="submit" value="ADD MOVIE">
</div>
{% endblock %}

movie/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body class="bg-warning">

<nav class="navbar navbar-light bg-danger">
  <div class="container-fluid">
    <a class="navbar-brand">Online Movies Shop</a>
    <form class="d-flex">
      <a class="btn btn-outline-success" href="{% url 'app1:add' %}">Add Movies</a>
    </form>
  </div>
</nav>
{% block content %}
{% endblock %}
</body>
</html>

movie/templates/detail.html
{% extends 'base.html' %}
{% load  static %}

{% block content %}
<h2>Movie List</h2>
<div class="container">
<div class="card mb-3" style="max-width: 540px;">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="{{movie.image.url}}" class="img-fluid rounded-start" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">{{movie.title}}</h5>
        <p class="card-text">{{movie.description}}</p>
        <p class="card-text"><small class="text-muted">{{movie.language}}</small></p>
          <a href="{% url 'app1:edit' movie.id%}" class="btn btn-danger">Edit</a>
          <a href="{% url 'app1:delete'  movie.id %}" class="btn btn-danger">Delete</a>
      </div>
    </div>
  </div>
</div>
</div>

{% endblock %}

movie/templates/edit.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<H2>MOVIES</H2>
<h2 class="text-center">Add Movies</h2>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-3">
  <label class="form-label">Title</label>
  <input type="text" class="form-control" name="t"  value="{{movie.title}}">
</div>
<div class="mb-3">
  <label class="form-label">Description</label>
  <input type="text" class="form-control"  name='d' value="{{movie.description}}" >
</div>
<div class="mb-3">
  <label class="form-label">year</label>
  <input type="number" class="form-control" name="y" value="{{movie.year}}" >
</div>

<div class="mb-3">
  <label class="form-label">language</label>
  <input type="text" class="form-control" name="l"  value="{{movie.language}}" placeholder="enter the language">
</div>



    <div class="mb-3">
  <label class="form-label">image</label>
        <img src="{{movie.image.url}}" height="100px"  width="100%">
  <input type="file" class="form-control" name="i" >
</div>
<div class="mb-3">
    <input type="submit" value="ADD MOVIE">
</div>
</form>
{% endblock %}

movie/templates/home.html
{% extends 'base.html' %}
{% load  static %}

{% block content %}
<h2>Movie List</h2>
<div class="container">
    <div class="row mt-5">
        {% for i in movie %}

        <div class="col-sm-4">
            <div class="card  mx-auto mb-5" style="width: 18rem;">
  <img src="{{i.image.url}}" class="card-img-top"   height="150px" width="100%" alt="...">
  <div class="card-body text-center">
    <h5 class="card-title">{{i.title}}</h5>
    <p class="card-text">{{i.year}}</p>
    <a href="{% url 'app1:detail' i.id %}" class="btn btn-danger">Details</a>
  </div>
</div></div>

        {% endfor %}
    </div>
</div>

{% endblock %}